services:
  - type: web
    name: real-estate-chatbot-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn realestate_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: realestate_api.settings
      - key: ALLOWED_HOSTS
        value: "*"
